---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  log_level: warning
  require_chef: false
  formula: docker
  state_top:
    base:
      '*':
        - docker.remove
        - docker
  pillars:
    top.sls:
      base:
        '*':
          - docker

platforms:
  - name: ubuntu-18.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales ifupdown apt-transport-https
        - locale-gen en_US.UTF-8
        - update-locale LANG=en_US.UTF-8
        - mkdir -p /run/sshd
      run_command: /lib/systemd/systemd
  - name: debian-stretch
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales ifupdown apt-transport-https
        - locale-gen en_US.UTF-8
      run_command: /lib/systemd/systemd
  - name: debian-jessie
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales ifupdown apt-transport-https
        - locale-gen en_US.UTF-8
      run_command: /lib/systemd/systemd
#   - name: centos-7
#     driver_config:
#       run_command: /lib/systemd/systemd

suites:
  - name: default
    provisioner:
      pillars:
        docker.sls:
          docker:
            use_upstream_repo: true
  - name: version-1.13.1
    provisioner:
      pillars:
        docker.sls:
          docker:
            version: '1.13.1*'
            use_old_repo: true
    excludes:
      - ubuntu-18.04
  - name: version-18
    provisioner:
      pillars:
        docker.sls:
          docker:
            version: '18.*'
            use_old_repo: true
    excludes:
      - debian-stretch
      - debian-jessie

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
